name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 21
      uses: actions/setup-node@v3
      with:
        node-version: 21
        cache: 'npm'
    - run: npm ci
    - run: npm run build 

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/polytech2024
        username: ${{ secrets.LOGIN }}
        password: ${{ secrets.MDP }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.gha
        push: true
        tags: rg.fr-par.scw.cloud/polytech2024/steven/front:v1